[package]
name = "opendp_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.81", features = ["full", "parsing"]}
quote = "1.0.10"
proc-macro2 = "1.0.32"